### ISSUE TITLE
Where is the font file?

### ISSUE THREAD

**Issue by zx2395** [UltimateNova1203/mgs2-pchd#3]
I want to know the location of the font file, but I can't find it.
Help me!

**Comment by UltimateNova1203** [comment]
Which font? The font database that the game uses, or the font used for the textures listed in MISC.md?

If it's the font database used by the game, it is included in the game files where you installed the game.

If it's the font as described in MISC.md, you'll have to source some of them yourself. Acumin Pro is provided by Adobe for cost, but there is a prototype-like version of it included with the Creative Suite. Stuff like Times New Roman and Lucida Console are usually pre-installed in your OS.

**Comment by zx2395** [comment]
First of all, thank you for your answer.
I don't know where the game files are installed.
The font I'm looking for is a caption font.

**Comment by UltimateNova1203** [comment]
i believe it is the file "font.row" if my memory serves correct. Probably is listed under `\MGS2\cdrom.img\font` or possibly in another folder under the `cdrom.img`. You won't be able to directly use it however, as it's a proprietary file format. I found some info on an older MGS Russian forum in the past, though the old link is down, but the contents are on it's current iteration (i think it's called Outer Heaven, with a .ru TLD).

**Comment by zx2395** [comment]
Thank you for your kind reply!
